### ISSUE TITLE
I can't get this working with latest expo version

### ISSUE THREAD

**Issue by JacobCooley** [kristerkari/react-native-css-modules#22]
I keep getting Unable to resolve "./App.scss" from "src/modules/app/App.js"
I put the correct babel plugins in .babelrc and put the packageOpts in my app.json.  Still not working :(

**Comment by kristerkari** [comment]
Thanks @JacobCooley!

I don't use Expo, so I haven't checked how the correct config looks like with the current Expo version. 

I can try with the latest Expo and see if I can get it to work.

**Comment by JacobCooley** [comment]
Why don't you use expo?  I'm just curious because I have a lot of native android experience and React.js experience, but I'm new to React Native

**Comment by kristerkari** [comment]
The reason why I don't use Expo is that I'm a so called "power user". I like to have full control over the React Native in my project and update the latest bug fixes as soon as they are released. Expo is a framework on top of React Native, so you lose most of that control as soon as you start using it. 

However, I really like Expo. They have a lot of great APIs that are not available in React Native and they seem to be releasing new features very often.

As you are new to React Native, I definitely recommend Expo. Try it out and If you feel that there is something limiting you with Expo, only then you should consider using regular React Native.

**Comment by kristerkari** [comment]
@JacobCooley I have updated the documentation with instructions how to setup the library with Expo. Please have a look and let me know if there is something missing.
