### ISSUE TITLE
I can't get this working with latest expo version too

### ISSUE THREAD

**Issue by lynnkoo** [kristerkari/react-native-css-modules#30]
The question likes https://github.com/kristerkari/react-native-css-modules/issues/22, but when I upgrade `expo-cli`, I can't get this working.
expo-cli version: 3.0.10
expo-sdk version: 34.0.0
Thanks

**Comment by kristerkari** [comment]
It's a breaking change by Expo, so make sure that you have `sourceExts`  defined in `app.json`, e.g. https://github.com/kristerkari/react-native-sass-transformer#step-2-configure-the-react-native-packager

**Comment by lynnkoo** [comment]
I resolved this question, thanks!
