### ISSUE TITLE
[Discussion] Node-sass is deprecated

### ISSUE THREAD

**Issue by VladimirTambovtsev** [kristerkari/react-native-css-modules#42]
Node-sass is deprecated right now - [https://www.npmjs.com/package/node-sass](https://www.npmjs.com/package/node-sass):
 _Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass._. 

Is it possible to migrate to Dart Sass - [https://www.npmjs.com/package/sass](https://www.npmjs.com/package/sass) in this documentation [https://github.com/kristerkari/react-native-css-modules/blob/master/docs/setup-sass.md](https://github.com/kristerkari/react-native-css-modules/blob/master/docs/setup-sass.md)?

**Comment by kristerkari** [comment]
@VladimirTambovtsev Thanks! indeed should migrate the docs to use Dart Sass.
