### ISSUE TITLE
SCSS not working for web

### ISSUE THREAD

**Issue by gihanrangana** [kristerkari/react-native-css-modules#47]
when i try to use scss on expo it works for mobile but on web it doesn't work,
on web when i import scss file it returns as a string like below

![image](https://github.com/kristerkari/react-native-css-modules/assets/24897554/bdbf438d-f220-4109-8f58-5245ce629719)

if i use metro bundler for web it works fine, but looks like metro bundler still doesn't have hot reload feature for web. any idea to fix this?

**Comment by gihanrangana** [comment]
@kristerkari see this repo, main is using metro bunbler, if you can check please use feature/webpack branch
https://github.com/gihanrangana/expo-sdk-48-sass-transformer-ts/tree/feature/webpack

**Comment by kristerkari** [comment]
@gihanrangana The reason why it does not work when you switch from Metro to Webpack is that the CSS modules are implemented in a different way when using Metro, so you can't use them like that in Webpack. 

Unfortunately it is not as easy I would like to setup the CSS modules for both React Native and Web.

What your project would need to make it work:

1.  You need to use the `className` prop since CSS modules for Web won't work with `style`.
2. As you are using Typescript, you would need to patch the React Native Typescript typings to support `className` (I have been maintaining custom typings here: https://github.com/kristerkari/react-native-types-for-css-modules).
3. Your Expo Webpack config should work if you use the the style that is used here: https://github.com/kristerkari/react-native-svg-expo-example/pull/1/files

I have an example of using React Native CSS modules with Typescript, but without Expo here:
https://github.com/kristerkari/react-native-css-modules-with-typescript-example

**Comment by kristerkari** [comment]
@gihanrangana of course if you are able to use Metro, then you can continue using it the way that you have it setup.

**Comment by gihanrangana** [comment]
> @gihanrangana of course if you are able to use Metro, then you can continue using it the way that you have it setup.

no hot reload isn't working for web on Metro. 



> @gihanrangana The reason why it does not work when you switch from Metro to Webpack is that the CSS modules are implemented in a different way when using Metro, so you can't use them like that in Webpack.
> 
> Unfortunately it is not as easy I would like to setup the CSS modules for both React Native and Web.
> 
> What your project would need to make it work:
> 
> 1. You need to use the `className` prop since CSS modules for Web (Webpack) won't work with `style`.
> 2. React Native Web has dropped support for the `className` prop, so it needs to be patched in (see: https://github.com/kristerkari/react-native-css-modules-with-typescript-example/tree/master/patches).
> 3. As you are using Typescript, you would need to patch the React Native Typescript typings to support `className` (I have been maintaining custom typings here: https://github.com/kristerkari/react-native-types-for-css-modules).
> 4. Your Expo Webpack config should work if you configure it the way that is used here: https://github.com/kristerkari/react-native-svg-expo-example/pull/1/files
> 
> I have an example of using React Native CSS modules with Typescript, but without Expo here: https://github.com/kristerkari/react-native-css-modules-with-typescript-example

will try this and let u know

**Comment by gihanrangana** [comment]
@kristerkari didn't work bro this is configs

package.json
```json
{
  "name": "expo-sdk-48-sass-transformer-ts",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.5",
    "expo-status-bar": "~1.4.4",
    "react": "^18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.8",
    "react-native-web": "~0.18.10"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.22.9",
    "@expo/webpack-config": "^18.0.1",
    "@types/react": "~18.0.27",
    "@types/react-native": "kristerkari/react-native-types-for-css-modules#v0.71.8",
    "autoprefixer": "^10.4.14",
    "babel-plugin-react-native-classname-to-style": "^1.2.2",
    "babel-plugin-react-native-platform-specific-extensions": "^1.1.1",
    "css-loader": "^6.8.1",
    "dts-css-modules-loader": "^2.0.1",
    "mini-css-extract-plugin": "^2.7.6",
    "node-sass": "^8.0.0",
    "postcss-loader": "^7.3.3",
    "react-native-sass-transformer": "^2.0.0",
    "react-native-typed-sass-transformer": "^0.11.0",
    "sass": "^1.64.0",
    "sass-loader": "^13.3.2",
    "typescript": "^4.9.4"
  },
  "private": true
}
```

webpack.config.js

```js

const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const autoprefixer = require('autoprefixer');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  config.module.rules.push(
    {
      test: /\.scss$/,
      use: [
        {
          loader: MiniCssExtractPlugin.loader,
        },
        {
          loader: 'dts-css-modules-loader',
          options: {
            namedExport: true,
            camelCase: true,
            modules: true,
            localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
          },
        },
        {
          loader: 'css-loader',
          options: {
            modules: {
              exportLocalsConvention: 'camelCaseOnly',
              localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
            },
          },
        },
        {
          loader: 'postcss-loader',
          options: {
            postcssOptions: {
              plugins: [autoprefixer()],
            },
          },
        },
        {
          loader: 'sass-loader',
        },
      ],
    },
  );

  config.plugins = config.plugins.concat(
    [
      new MiniCssExtractPlugin()
    ]
  );


  return config;
};
```

already pushed to the my repo webpack branch

**Comment by gihanrangana** [comment]
@kristerkari i have fixed it with metro bro, now scss works better with metro bundler for both web and mobile.
you can see in this repo
https://github.com/gihanrangana/expo-sdk-48-sass-transformer-ts/tree/master

Solutions:
```cmd
yarn add -D @expo/metro-runtime
```

entry file shout import `@expo/metro-runtime`
```js
//entry file
import { registerRootComponent } from "expo";
import App from "./src/App";
import '@expo/metro-runtime'

registerRootComponent(App)
```
